return {}
-- return { "yetone/avante.nvim", version = false }
-- return {
--     "yetone/avante.nvim",
--     -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--     -- ⚠️ must add this setting! ! !
--     build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
--         or "make",
--     event = "VeryLazy",
--     -- lazy = false,
--     version = false, -- set this if you want to always pull the latest change
--     ---@module 'avante'
--     ---@type avante.Config
--     opts = {
--         -- add any opts here
--         -- this file can contain specific instructions for your project
--         instructions_file = "avante.md",
--         -- add any opts here
--         provider = "deepseek",
--         -- provider = "copilot",
--         -- auto_suggestions_provider = "openai",
--         selector = {
--             provider = "snacks",
--         },
--         providers = {
--             deepseek = {
--                 __inherited_from = "openai",
--                 api_key_name = "DEEPSEEK_API_KEY",
--                 endpoint = "https://api.deepseek.com",
--                 model = "deepseek-chat",
--                 -- model = "deepseek-coder",
--                 -- model = "deepseek-reasoner",
--                 max_tokens = 8192,
--                 -- extra_request_body = {
--                 --   temperature = 0,
--                 -- },
--             },
--         },
--     },
--     dependencies = {
--         "nvim-treesitter/nvim-treesitter",
--         "stevearc/dressing.nvim",
--         "nvim-lua/plenary.nvim",
--         "MunifTanjim/nui.nvim",
--         --- The below dependencies are optional,
--         {
--             -- support for image pasting
--             "HakonHarnes/img-clip.nvim",
--             event = "VeryLazy",
--             opts = {
--                 -- recommended settings
--                 default = {
--                     embed_image_as_base64 = false,
--                     prompt_for_file_name = false,
--                     drag_and_drop = {
--                         insert_mode = true,
--                     },
--                     -- required for Windows users
--                     use_absolute_path = true,
--                 },
--             },
--         },
--         {
--             -- Make sure to set this up properly if you have lazy=true
--             "MeanderingProgrammer/render-markdown.nvim",
--             opts = {
--                 file_types = { "markdown", "Avante" },
--             },
--             -- ft = { "markdown", "Avante" },
--         },
--     },
-- }
